# Generated by Django 5.1.1 on 2024-09-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
