# Generated by Django 5.1.1 on 2024-10-11 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_usermessage_email_usermessage_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='staff',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
